server:
  port: 8086

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: admin
    realmImportFile: resource-microservices-realm.json
logging:
  level:
    org.keycloak: DEBUG