server:
  port: 8081
spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: jdbc:postgresql://localhost:5432/song_metadata
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    prefer-ip-address: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka