version: '3.7'
networks:
  my_network:
    external: true
services:
  resource-db:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - ${GLOBAL_NETWORK}
    container_name: resource-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./resource-service/init.sql:/docker-entrypoint-initdb.d/init.sql
  song-db:
    image: postgres
    ports:
      - "15999:5432"
    networks:
      - ${GLOBAL_NETWORK}
    container_name: song-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./song-service/init.sql:/docker-entrypoint-initdb.d/init.sql
  resource-service:
    build: ./resource-service
    volumes:
      - C:/Users/Sergey_Pil/.gradle:/home/gradle/.gradle
    networks:
      - ${GLOBAL_NETWORK}
    container_name: resource-service
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: eureka-compose
    depends_on:
      - resource-db
      - discovery-service
  resource-service-2:
    build: ./resource-service
    volumes:
      - C:/Users/Sergey_Pil/.gradle:/home/gradle/.gradle
    networks:
      - ${GLOBAL_NETWORK}
    container_name: resource-service-2
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      SPRING_PROFILES_ACTIVE: eureka-compose
    depends_on:
      - resource-db
      - discovery-service
  song-service:
    build: ./song-service
    volumes:
      - C:/Users/Sergey_Pil/.gradle:/home/gradle/.gradle
    networks:
      - ${GLOBAL_NETWORK}
    container_name: song-service
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      SPRING_PROFILES_ACTIVE: eureka-compose
    depends_on:
      - song-db
      - discovery-service
  song-service-2:
    build: ./song-service
    volumes:
      - C:/Users/Sergey_Pil/.gradle:/home/gradle/.gradle
    networks:
      - ${GLOBAL_NETWORK}
    container_name: song-service-2
    ports:
      - "8083:8083"
    environment:
      SERVER_PORT: 8083
      SPRING_PROFILES_ACTIVE: eureka-compose
    depends_on:
      - song-db
      - discovery-service
  discovery-service:
    build: ./discovery-service
    volumes:
      - C:/Users/Sergey_Pil/.gradle:/home/gradle/.gradle
    networks:
      - ${GLOBAL_NETWORK}
    container_name: discovery-service
    ports:
      - "8761:8761"
