{
 "title": "JVM memory used in microservices",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Resource API Gateway JVM memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"resource-api-gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage service JVM memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"storage-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource processor service JVM memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"resource-processor-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Song service JVM memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"song-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource service JVM memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"resource-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}