{
 "title": "API Gateway",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "HTTP server requests seconds sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_client_requests_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP server requests active seconds duration max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_server_requests_active_seconds_duration_sum{job=\"resource-api-gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP server requests seconds max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{job=\"resource-api-gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}