scrape_configs:
  - job_name: resource-service
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['resource-service:8080']
  - job_name: song-service
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['song-service:8081']
  - job_name: resource-processor-service
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['resource-processor-service:8082']
  - job_name: resource-api-gateway
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['resource-api-gateway:8084']
  - job_name: storage-service
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['storage-service:8085']
