server:
  port: 8080
spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: jdbc:postgresql://resource-db-service:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: resource-service

clients:
  song-service:
    url:  http://song-service:8081/songs
