version: "3.8"

services:
  localstack:
    image: localstack/localstack
    container_name: local_aws_s3
    restart: always
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
    volumes:
      - './localstack_data:/tmp/mylocalstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672