spring:
  cloud:
    gateway:
      routes:
        - id: resource-service
          uri: lb://resource-service
          predicates:
            - Path=/resource/**
        - id: resource-processor
          uri: lb://resource-processor
          predicates:
            - Path=/processor/**
        - id: song-service
          uri: lb://song-service
          predicates:
            - Path=/song/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/