apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-service
  namespace: songs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: song-service
  template:
    metadata:
      labels:
        app: song-service
    spec:
      containers:
      - name: song-service
        image: song-service-image:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: SERVER_PORT
            value: "8081"
          - name: SPRING_PROFILES_ACTIVE
            value: k8s