server:
  port: 8080
spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: jdbc:postgresql://localhost:5432/audio
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    enabled: false
clients:
  storage-service:
    url: http://localhost:8085/storages
logstash:
  destination: localhost:5044
aws:
  url: http://localhost:4566