server:
  port: ${SERVER_PORT}
spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: jdbc:postgresql://resource-db:5432/audio
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
aws:
  url: http://localstack:4566
eureka:
  client:
    prefer-ip-address: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka
clients:
  storage-service:
    url: http://localhost:8085/api/storages