server:
  port: 8080
spring:
  zipkin:
    base-url: http://localhost:9411
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: jdbc:postgresql://localhost:5432/audio
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    prefer-ip-address: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logstash:
  destination: localhost:5044
clients:
  storage-service:
    url: http://storage-service/storages
aws:
  url: http://localhost:4566