spring:
  application:
    name: resource-service
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    enabled: true
    propagation:
      type: b3
    sampling:
      probability: 1.0
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
aws:
  url: http://localhost:4566
clients:
  storage-service:
    url: http://storage-service/storages
logstash:
  destination: localhost:5044