server:
  port: ${SERVER_PORT}
spring:
  application:
    name: resource-processor-service
  zipkin:
    base-url: http://zipkin:9411/
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

clients:
  song-service:
    url: http://song-service:8081/songs
  resource-service:
    url: http://resource-service:8080/resources
eureka:
  client:
    enabled: false
logstash:
  destination: logstash:5044
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans