server:
  port: ${SERVER_PORT}
spring:
  application:
    name: resource-processor-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
clients:
  song-service:
    url: http://SONG-SERVICE/songs
  resource-service:
    url: http://RESOURCE-SERVICE/resources
eureka:
  client:
    prefer-ip-address: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka
