server:
  port: 8082

#spring:
#  rabbitmq:
#    host: localhost
#    port: 64285
#    username: guest
#    password: guest
#  
clients:
  song-service:
    url: http://localhost:8081/songs
  resource-service:
    url: http://localhost:8080/resources