apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-configmap
  namespace: {{ .Values.namespace }}
  labels:
    date: {{ template "mychart.currentdate" . }}
    version: {{ template "mychart.version" . }}
data:
  server.port: "8080"
  spring.profiles.active: "k8s"