apiVersion: v1
kind: Service
metadata:
  name: resource-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: resource-service
  ports:
    - protocol: TCP
      port: 8080