server:
  port: 8085
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8086/auth/realms/resource-microservices
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: jdbc:postgresql://localhost:5432/storage
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
eureka:
  client:
    prefer-ip-address: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logstash:
  destination: localhost:5044